group: deprecated-2017Q2
sudo: required
services:
- docker
language: nix
deploy:
  provider: script
  script: make dockerize && make docker-push
  on:
    repo: smarkets/marge-bot
    tags: true
    condition: "$TRAVIS_TAG = $(cat version)"
env:
  global:
    # smarkets ci docker username
  - secure: vjoKmdKJqA7qSkTSbURAV9ViisgeDIKthK7JSgyG78VlY/pYDHwGf9Fs4Mg+kRvaYMf+4bdIxNWkbPs/dWo4MRqkYrOn4MDGivRIzlLBhsVHIPKNNTsJHOuT19EuqrgNhn94usTZMLw3kc9NkJQ+ccJta6FNL5C8jzzTVo2CKsi/WTP4uqv/TiyNXUqD0OcOiuXP3njmdQPpUtqqghIYbaku0Rb5XqjSjZ8Z8foVy5NAcwo/CVC+MZq3KnfKza5EsSrbWJzTjKCnIcTPRXXNsvUciqqrJTbAiLq3IHYpMmSg1quXPbqONezTgsMn7ogkULKqupOi98vvzkeYX/clvtc2Jw46w1n6BhsFOT7lPu/m/MOwggWYkrhuO5EH89XEBSA2s6OJ2d39WYH11y+zCBGf5xOCosSHpKTvOsMO7JB2Gpy0TinFWdX6wnQoyZrqsFlL1SuOcxuZ5P7yzCuiGNSlRlthQD1gM53p3icPLzP71+OkuaVX5ZmNGUHE1szm0hCBKCUNqrHkbynGVSy/fzhThI6PzYXRKTF178SdGtks4gOmR8DfDWOS3ahOtZUDOyTSkaKFsEuVbG+owzzSP0OTULdBcu2B2i/JWqK6lnRcTRVGaGldtuSNqamExPQRuCpjX/zReSNDv249kPh/XP0Y0vboCCbr+grRvF3WtCI=
    # smarkets ci docker password
  - secure: s1relp0LqRUqsi8JQaIPCmUpcRVgSqvTZW6oIGB1e44gAgMTRjSJ3zQqXgIqbm6GLw3oWSfSS3wfeXZNz6ZvOxSnb3rDLP6HZe04bh2m+99Pvc7mg5CEeNbRi3d3NRbA6yCCLxYiAEXMtyQeMPic+JYd+TqOxhHOZufig3ATQtyUMmU0qNXgzAh1AJGSmIEq2iPY5o1zWyjJGrWD+LHfjNO9P6KgUSSVLxSR/VvXy8hdeR2dahUmBxcARwF9TF0sh0PyF2T8UbSOIjwa/p2rDy1e+1ITQxe/AIUnlSeINEPdZ6gNyf/ZKi7ZAlPS9UsA1MEARhjSJefydODXRC2a1neeuRsSNuZUhoGdiHEOupb6ufjK/D2H2xwohfZ0yLD4T+0pt/EeRmwTxSB0ANuUZ8mdloNlEahryRwIpIaVh2V5meNlQK2CzoKru+nbHR8ezPs8vLy8+Da+MiY7FtSuLlaNFpywP7Lz4hv863JgtPlhkR3X1lvNa4naO68cklte4tjuU0Y1KUEeuOg0VFPO9BJnLSSzNaAh/hG/ocxAIxk0Zez+vBXtjq2pxKV3hYosImFn8EgXZOd0Z/gyqQ2YPfixlaNgGgUOq0l3304EtTLBgO9u7dZN5SPd5xXk9m1XYPuOLlSvcV4KtxOWVSn2kx16A6TWhmyptSCwNSTEDrQ=
